#!/bin/bash
set -eux


VERSION="$(git tag --points-at)"
if [[ ! -n $VERSION ]]; then
    >&2 echo "Dirty build!"
    VERSION="$(git rev-parse --short HEAD)"
fi


function rebuild {
    local res="$1"
    local browser="$2"
    ./build --target "$browser" --release --lint
    zip -r -j "$res" dist/*
    unzip -l "$res"
}

for browser in "chrome" "firefox"; do
    rebuild "grasp-$VERSION-$browser.zip" "$browser"
done
