#!/bin/bash
set -eux


VERSION="$(git tag --points-at)"
if [[ ! -n $VERSION ]]; then
    >&2 echo "Dirty build!"
    VERSION="$(git rev-parse --short HEAD)"
fi


function rebuild {
    local res="$1"
    npm run build
    zip -r -j "$res" build/*
    unzip -l "$res"
}

for browser in "chrome" "firefox"; do
    TARGET="$browser" rebuild "grasp-$VERSION-$browser.zip"
done
