#!/bin/bash
set -eux


VERSION="$(git tag --points-at)"
if [[ ! -n $VERSION ]]; then
    >&2 echo "Dirty build!"
    VERSION="$(git rev-parse --short HEAD)"
fi
   

OUT="grasp-$VERSION.zip"

npm run build
zip -r -j "$OUT" build/*
unzip -l "$OUT"
