#!/bin/bash
curl -X POST "$1" \
     -H "Content-Type: application/json" \
     -d '{
       "title": "123",
       "url": "test",
       "selection": null,
       "comment": null,
       "tag_str": null
     }'
