* Running end2end tests

There are some end2end tests which check both web extension in a browser + backend functionality.

There are two flavours: `headless` and `gui`.

Headless run the browsers in headless mode (no GUI), so they are the ones running on github actions.

GUI ones require a visible browser window, and need to be run manually. For these, you'll need:
- `xdotool` installed (it's used for simulating keyboard input).
  I'm not sure if there is a decent alternative for OSX, so these only work on Linux.
- They won't work on Wayland right now (need X11).

Necessary browsers and webdrivers should be installed automatically by selenium (via "selenium manager").

Some example commands to run the tests:

: tox -e end2end -- -s  # runs all available tests with all browsers. -s is necessary to confirm prompts
: tox -e end2end -- -s --collect-only  # to see all available tests
: tox -e end2end -- -s -k headless  # only run tests on headless firefox/chrome
: tox -e end2end -- -s -k 'firefox_gui and bad_port'  # only run one specific test against gui firefox

Some tips:
- It's useful to pass =--pdb= to pytest, so you can inspect the browser state if something goes wrong.
- When you're in development/debugging process, perhaps best to run the firefox version of tests -- Chrome has a 5-ish seconds lag after installing the extension for some reason.
- Since these tests can be quite slow, =-n auto= flag to parallelize can be helpful (via =pytest-xdist=).
- To debug flaky tests, it's useful to use =--count=N= flag (via =pytest-repeat=).

* Releasing extension

- bump extension =version= and =version_name= in =extension/package.json=
- commit your changes (the build script expects a clean git state)

** AMO (addons.mozilla.org)

https://addons.mozilla.org/en-US/developers/addon/grasp/edit

: cd extension
: npm install # (if necessary)
: source ./webext_secrets.sh  # puts api key/secret in the environment
: ./build --firefox --lint --release --publish unlisted/listed

The =web-ext sign= command will wait in a loop until the extension is approved on addons.mozilla.org.

Note:
- even in =unlisted= case, seems like there is some (~5m?) wait before automatic approval.
- seems like to install unlisted extension, you have to install it manually from the AMO page (it won't autoupdate even if you had unlisted version installed before).


** CWS (chrome web store)

https://chrome.google.com/u/1/webstore/devconsole

You'll need OAuth credentials for uploading the extension, see [this guide](https://github.com/fregante/chrome-webstore-upload-keys).
Note that they can expire after 6 month, so may not be worth doing it via CLI and just do a browser upload.

: cd extension
: npm install # (if necessary)
: source ./cws_secrets.sh  # puts api key/secret in the environment
: ./build --chrome --lint --release --publish listed

This will upload and publish the new version. It will submit it for review, and the CWS page should have 'pending review' status now.

Note:
- it [seems](https://developer.chrome.com/docs/extensions/develop/migrate/publish-mv3#publish-beta) that CWS doesn't support something similar to "unlisted" version, and would require a whole separate "beta" extension? 